export const PERMALINKS = {
  home: '/',
  home1: '/home-1/',
  home2: '/home-2/',
  portfolio: '/portfolio/',
  portfolioGrid: '/portfolio/grid/',
  portfolioWide: '/portfolio/wide/',
  portfolioSlider: '/portfolio/slider/',
  services: '/services/',
  team: '/team/',
  gallery: '/gallery/',
  publications: '/publications/',
  contact: '/contact/',
  blog: '/blog/',
  notFound: '/404.html',
  projects: {
    interiorDesignStudio: '/projects/interior-design-studio/',
    skincareBrand: '/projects/skincare-brand/',
    cascadeOfLava: '/projects/cascade-of-lava/',
    airPurifier: '/projects/air-purifier/',
    chocolateBrand: '/projects/chocolate-brand/',
    homeSecurityCamera: '/projects/home-security-camera/',
  },
  servicesDetail: {
    brandStrategy: '/services/brand-strategy/',
  },
  publicationsDetail: {
    editablePortfolioSystem: '/publications/editable-portfolio-system/',
  },
  blogDetail: {
    creativePortfolioSystems: '/blog/creative-portfolio-systems/',
  },
};

export const LEGACY_HTML_REDIRECTS = {
  '/home-1.html': PERMALINKS.home1,
  '/home-2.html': PERMALINKS.home2,
  '/portfolio-1.html': PERMALINKS.portfolio,
  '/portfolio-2.html': PERMALINKS.portfolioGrid,
  '/portfolio-3.html': PERMALINKS.portfolioSlider,
  '/project-1.html': PERMALINKS.projects.interiorDesignStudio,
  '/project-2.html': PERMALINKS.projects.skincareBrand,
  '/project-3.html': PERMALINKS.projects.cascadeOfLava,
  '/project-4.html': PERMALINKS.projects.airPurifier,
  '/project-5.html': PERMALINKS.projects.chocolateBrand,
  '/project-6.html': PERMALINKS.projects.homeSecurityCamera,
  '/services.html': PERMALINKS.services,
  '/service.html': PERMALINKS.servicesDetail.brandStrategy,
  '/team.html': PERMALINKS.team,
  '/blog.html': PERMALINKS.blog,
  '/blog-inner.html': PERMALINKS.blogDetail.creativePortfolioSystems,
  '/publication.html': PERMALINKS.publications,
  '/contact.html': PERMALINKS.contact,
};
